sudo: required
services:
  - docker

before_install:
  - docker build -t dinpandy/docker-react -f Dockerfile.dev .

script:
  - docker run dinpandy/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker_react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-443590094270"
  bucket_path: "docker_react"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY